# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPayments_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPayments_form(object):
    def setupUi(self, AddPayments_form):
        AddPayments_form.setObjectName("AddPayments_form")
        AddPayments_form.setEnabled(True)
        AddPayments_form.resize(400, 317)
        self.Name_Form_AddPaymentForm = QtWidgets.QLabel(AddPayments_form)
        self.Name_Form_AddPaymentForm.setGeometry(QtCore.QRect(10, 10, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Name_Form_AddPaymentForm.setFont(font)
        self.Name_Form_AddPaymentForm.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_Form_AddPaymentForm.setObjectName("Name_Form_AddPaymentForm")
        self.Categoty_box = QtWidgets.QComboBox(AddPayments_form)
        self.Categoty_box.setGeometry(QtCore.QRect(70, 110, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Categoty_box.setFont(font)
        self.Categoty_box.setEditable(True)
        self.Categoty_box.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.Categoty_box.setModelColumn(0)
        self.Categoty_box.setObjectName("Categoty_box")
        self.Add_button = QtWidgets.QPushButton(AddPayments_form)
        self.Add_button.setGeometry(QtCore.QRect(300, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Add_button.setFont(font)
        self.Add_button.setObjectName("Add_button")
        self.label = QtWidgets.QLabel(AddPayments_form)
        self.label.setGeometry(QtCore.QRect(70, 90, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.date_dateEdit = QtWidgets.QDateEdit(AddPayments_form)
        self.date_dateEdit.setGeometry(QtCore.QRect(70, 170, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_dateEdit.setFont(font)
        self.date_dateEdit.setObjectName("date_dateEdit")
        self.label_2 = QtWidgets.QLabel(AddPayments_form)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Price_Box = QtWidgets.QSpinBox(AddPayments_form)
        self.Price_Box.setGeometry(QtCore.QRect(70, 230, 261, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Price_Box.setFont(font)
        self.Price_Box.setMaximum(999999999)
        self.Price_Box.setObjectName("Price_Box")
        self.label_3 = QtWidgets.QLabel(AddPayments_form)
        self.label_3.setGeometry(QtCore.QRect(70, 210, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Wrong_label = QtWidgets.QLabel(AddPayments_form)
        self.Wrong_label.setEnabled(False)
        self.Wrong_label.setGeometry(QtCore.QRect(10, 45, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Wrong_label.setFont(font)
        self.Wrong_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Wrong_label.setObjectName("Wrong_label")

        self.retranslateUi(AddPayments_form)
        QtCore.QMetaObject.connectSlotsByName(AddPayments_form)

    def retranslateUi(self, AddPayments_form):
        _translate = QtCore.QCoreApplication.translate
        AddPayments_form.setWindowTitle(_translate("AddPayments_form", "Form"))
        self.Name_Form_AddPaymentForm.setText(_translate("AddPayments_form", "Новый платеж"))
        self.Add_button.setText(_translate("AddPayments_form", "Добавить"))
        self.label.setText(_translate("AddPayments_form", "Категория:"))
        self.label_2.setText(_translate("AddPayments_form", "Дата:"))
        self.label_3.setText(_translate("AddPayments_form", "Стоимость:"))
        self.Wrong_label.setText(_translate("AddPayments_form", "Платеж успешно добавлен"))
