# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BudgetsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BudgetsWindow(object):
    def setupUi(self, BudgetsWindow):
        BudgetsWindow.setObjectName("BudgetsWindow")
        BudgetsWindow.resize(841, 385)
        self.centralwidget = QtWidgets.QWidget(BudgetsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Mail = QtWidgets.QLabel(self.centralwidget)
        self.Label_Mail.setGeometry(QtCore.QRect(520, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_Mail.setFont(font)
        self.Label_Mail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_Mail.setObjectName("Label_Mail")
        self.Name_Window_HistoryWindow = QtWidgets.QLabel(self.centralwidget)
        self.Name_Window_HistoryWindow.setEnabled(True)
        self.Name_Window_HistoryWindow.setGeometry(QtCore.QRect(40, 10, 191, 70))
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(40)
        self.Name_Window_HistoryWindow.setFont(font)
        self.Name_Window_HistoryWindow.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Name_Window_HistoryWindow.setObjectName("Name_Window_HistoryWindow")
        self.Back_button = QtWidgets.QPushButton(self.centralwidget)
        self.Back_button.setGeometry(QtCore.QRect(750, 10, 75, 23))
        self.Back_button.setObjectName("Back_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 40, 400, 240))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Graphics/pop.png"))
        self.label.setObjectName("label")
        self.NullRemind_label = QtWidgets.QLabel(self.centralwidget)
        self.NullRemind_label.setGeometry(QtCore.QRect(20, 80, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NullRemind_label.setFont(font)
        self.NullRemind_label.setObjectName("NullRemind_label")
        BudgetsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BudgetsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 21))
        self.menubar.setObjectName("menubar")
        BudgetsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BudgetsWindow)
        self.statusbar.setObjectName("statusbar")
        BudgetsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BudgetsWindow)
        QtCore.QMetaObject.connectSlotsByName(BudgetsWindow)

    def retranslateUi(self, BudgetsWindow):
        _translate = QtCore.QCoreApplication.translate
        BudgetsWindow.setWindowTitle(_translate("BudgetsWindow", "MainWindow"))
        self.Label_Mail.setText(_translate("BudgetsWindow", "Example@mail.ru"))
        self.Name_Window_HistoryWindow.setText(_translate("BudgetsWindow", "Budgets"))
        self.Back_button.setText(_translate("BudgetsWindow", "Назад"))
        self.NullRemind_label.setText(_translate("BudgetsWindow", "У Вас еще нет ни одного платежа"))
