# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangeLogin_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeLogin_form(object):
    def setupUi(self, ChangeLogin_form):
        ChangeLogin_form.setObjectName("ChangeLogin_form")
        ChangeLogin_form.setEnabled(True)
        ChangeLogin_form.resize(400, 265)
        self.Name_Form_AddPaymentForm = QtWidgets.QLabel(ChangeLogin_form)
        self.Name_Form_AddPaymentForm.setGeometry(QtCore.QRect(10, 10, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Name_Form_AddPaymentForm.setFont(font)
        self.Name_Form_AddPaymentForm.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_Form_AddPaymentForm.setObjectName("Name_Form_AddPaymentForm")
        self.Add_button = QtWidgets.QPushButton(ChangeLogin_form)
        self.Add_button.setGeometry(QtCore.QRect(270, 220, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Add_button.setFont(font)
        self.Add_button.setObjectName("Add_button")
        self.label_2 = QtWidgets.QLabel(ChangeLogin_form)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Succsess_label = QtWidgets.QLabel(ChangeLogin_form)
        self.Succsess_label.setEnabled(False)
        self.Succsess_label.setGeometry(QtCore.QRect(10, 45, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Succsess_label.setFont(font)
        self.Succsess_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Succsess_label.setObjectName("Succsess_label")
        self.Input_login_change = QtWidgets.QLineEdit(ChangeLogin_form)
        self.Input_login_change.setGeometry(QtCore.QRect(70, 110, 251, 20))
        self.Input_login_change.setObjectName("Input_login_change")
        self.Input_login_change_2 = QtWidgets.QLineEdit(ChangeLogin_form)
        self.Input_login_change_2.setGeometry(QtCore.QRect(70, 180, 251, 20))
        self.Input_login_change_2.setObjectName("Input_login_change_2")
        self.label_4 = QtWidgets.QLabel(ChangeLogin_form)
        self.label_4.setGeometry(QtCore.QRect(70, 150, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(ChangeLogin_form)
        QtCore.QMetaObject.connectSlotsByName(ChangeLogin_form)

    def retranslateUi(self, ChangeLogin_form):
        _translate = QtCore.QCoreApplication.translate
        ChangeLogin_form.setWindowTitle(_translate("ChangeLogin_form", "Form"))
        self.Name_Form_AddPaymentForm.setText(_translate("ChangeLogin_form", "Сменить логин"))
        self.Add_button.setText(_translate("ChangeLogin_form", "подтвердить"))
        self.label_2.setText(_translate("ChangeLogin_form", "Новый логин:"))
        self.Succsess_label.setText(_translate("ChangeLogin_form", "Логин успешно изменен"))
        self.label_4.setText(_translate("ChangeLogin_form", "Прошлый логин:"))
