# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graphics_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphicsFrom(object):
    def setupUi(self, GraphicsFrom):
        GraphicsFrom.setObjectName("GraphicsFrom")
        GraphicsFrom.resize(800, 600)
        self.label = QtWidgets.QLabel(GraphicsFrom)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.label.setObjectName("label")

        self.retranslateUi(GraphicsFrom)
        QtCore.QMetaObject.connectSlotsByName(GraphicsFrom)

    def retranslateUi(self, GraphicsFrom):
        _translate = QtCore.QCoreApplication.translate
        GraphicsFrom.setWindowTitle(_translate("GraphicsFrom", "Form"))
        self.label.setText(_translate("GraphicsFrom", "TextLabel"))
