# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HistoryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryWindow(object):
    def setupUi(self, HistoryWindow):
        HistoryWindow.setObjectName("HistoryWindow")
        HistoryWindow.resize(832, 200)
        self.centralwidget = QtWidgets.QWidget(HistoryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Name_Window_HistoryWindow = QtWidgets.QLabel(self.centralwidget)
        self.Name_Window_HistoryWindow.setEnabled(True)
        self.Name_Window_HistoryWindow.setGeometry(QtCore.QRect(30, 10, 171, 70))
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(40)
        self.Name_Window_HistoryWindow.setFont(font)
        self.Name_Window_HistoryWindow.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Name_Window_HistoryWindow.setObjectName("Name_Window_HistoryWindow")
        self.Label_Mail = QtWidgets.QLabel(self.centralwidget)
        self.Label_Mail.setGeometry(QtCore.QRect(510, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_Mail.setFont(font)
        self.Label_Mail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_Mail.setObjectName("Label_Mail")
        self.Back_button = QtWidgets.QPushButton(self.centralwidget)
        self.Back_button.setGeometry(QtCore.QRect(740, 10, 75, 23))
        self.Back_button.setObjectName("Back_button")
        self.AddPayments_button = QtWidgets.QPushButton(self.centralwidget)
        self.AddPayments_button.setGeometry(QtCore.QRect(650, 50, 151, 23))
        self.AddPayments_button.setObjectName("AddPayments_button")
        self.NullHistory_label = QtWidgets.QLabel(self.centralwidget)
        self.NullHistory_label.setGeometry(QtCore.QRect(40, 90, 771, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NullHistory_label.setFont(font)
        self.NullHistory_label.setObjectName("NullHistory_label")
        HistoryWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HistoryWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setObjectName("menubar")
        HistoryWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HistoryWindow)
        self.statusbar.setObjectName("statusbar")
        HistoryWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HistoryWindow)
        QtCore.QMetaObject.connectSlotsByName(HistoryWindow)

    def retranslateUi(self, HistoryWindow):
        _translate = QtCore.QCoreApplication.translate
        HistoryWindow.setWindowTitle(_translate("HistoryWindow", "MainWindow"))
        self.Name_Window_HistoryWindow.setText(_translate("HistoryWindow", "History"))
        self.Label_Mail.setText(_translate("HistoryWindow", "Example@mail.ru"))
        self.Back_button.setText(_translate("HistoryWindow", "Назад"))
        self.AddPayments_button.setText(_translate("HistoryWindow", "Добавить платеж"))
        self.NullHistory_label.setText(_translate("HistoryWindow", "У Вас еще не было платежей"))
